[wokwi]
version = 1
firmware = '.pio\build\ESP32\firmware.bin'
elf = '.pio\build\ESP32\firmware.elf'
rfc2217ServerPort = 4000

# Encaminhe http://localhost:8180 para a porta 80 no ESP32 simulado:
[[net.forward]]
from = "localhost:8180"
to = "device:80"